#ifndef PROXY_H
#define PROXY_H

#include "stdafx.h"

#define DECLARE_PROXY(module, function) \
    PVOID module##_##function; \
    __declspec(naked) void WINAPIV _jmp_##module##_##function##(void) { __asm { jmp module##_##function } } \
    __pragma(comment(linker, "/EXPORT:" #function "=?_jmp_" #module "_" #function "@@YAXXZ"))

#define IMPLEMENT_PROXY(module, function) \
    module##_##function = GetProcAddress(module, #function);

/* Installable driver support */
DECLARE_PROXY(winmm, CloseDriver)
DECLARE_PROXY(winmm, OpenDriver)
DECLARE_PROXY(winmm, SendDriverMessage)
DECLARE_PROXY(winmm, DrvGetModuleHandle)
DECLARE_PROXY(winmm, GetDriverModuleHandle)
DECLARE_PROXY(winmm, DefDriverProc)
/* Sound support */
DECLARE_PROXY(winmm, sndPlaySoundA)
DECLARE_PROXY(winmm, sndPlaySoundW)
DECLARE_PROXY(winmm, PlaySoundA)
DECLARE_PROXY(winmm, PlaySoundW)
/* Waveform audio support */
DECLARE_PROXY(winmm, waveOutGetNumDevs)
DECLARE_PROXY(winmm, waveOutGetDevCapsA)
DECLARE_PROXY(winmm, waveOutGetDevCapsW)
DECLARE_PROXY(winmm, waveOutGetVolume)
DECLARE_PROXY(winmm, waveOutSetVolume)
DECLARE_PROXY(winmm, waveOutGetErrorTextA)
DECLARE_PROXY(winmm, waveOutGetErrorTextW)
DECLARE_PROXY(winmm, waveOutOpen)
DECLARE_PROXY(winmm, waveOutClose)
DECLARE_PROXY(winmm, waveOutPrepareHeader)
DECLARE_PROXY(winmm, waveOutUnprepareHeader)
DECLARE_PROXY(winmm, waveOutWrite)
DECLARE_PROXY(winmm, waveOutPause)
DECLARE_PROXY(winmm, waveOutRestart)
DECLARE_PROXY(winmm, waveOutReset)
DECLARE_PROXY(winmm, waveOutBreakLoop)
DECLARE_PROXY(winmm, waveOutGetPosition)
DECLARE_PROXY(winmm, waveOutGetPitch)
DECLARE_PROXY(winmm, waveOutSetPitch)
DECLARE_PROXY(winmm, waveOutGetPlaybackRate)
DECLARE_PROXY(winmm, waveOutSetPlaybackRate)
DECLARE_PROXY(winmm, waveOutGetID)
DECLARE_PROXY(winmm, waveOutMessage)
DECLARE_PROXY(winmm, waveInGetNumDevs)
DECLARE_PROXY(winmm, waveInGetDevCapsA)
DECLARE_PROXY(winmm, waveInGetDevCapsW)
DECLARE_PROXY(winmm, waveInGetErrorTextA)
DECLARE_PROXY(winmm, waveInGetErrorTextW)
DECLARE_PROXY(winmm, waveInOpen)
DECLARE_PROXY(winmm, waveInClose)
DECLARE_PROXY(winmm, waveInPrepareHeader)
DECLARE_PROXY(winmm, waveInUnprepareHeader)
DECLARE_PROXY(winmm, waveInAddBuffer)
DECLARE_PROXY(winmm, waveInStart)
DECLARE_PROXY(winmm, waveInStop)
DECLARE_PROXY(winmm, waveInReset)
DECLARE_PROXY(winmm, waveInGetPosition)
DECLARE_PROXY(winmm, waveInGetID)
DECLARE_PROXY(winmm, waveInMessage)
/* MIDI audio support */
DECLARE_PROXY(winmm, midiOutGetNumDevs)
DECLARE_PROXY(winmm, midiStreamOpen)
DECLARE_PROXY(winmm, midiStreamClose)
DECLARE_PROXY(winmm, midiStreamProperty)
DECLARE_PROXY(winmm, midiStreamPosition)
DECLARE_PROXY(winmm, midiStreamOut)
DECLARE_PROXY(winmm, midiStreamPause)
DECLARE_PROXY(winmm, midiStreamRestart)
DECLARE_PROXY(winmm, midiStreamStop)
DECLARE_PROXY(winmm, midiConnect)
DECLARE_PROXY(winmm, midiDisconnect)
DECLARE_PROXY(winmm, midiOutGetDevCapsA)
DECLARE_PROXY(winmm, midiOutGetDevCapsW)
DECLARE_PROXY(winmm, midiOutGetVolume)
DECLARE_PROXY(winmm, midiOutSetVolume)
DECLARE_PROXY(winmm, midiOutGetErrorTextA)
DECLARE_PROXY(winmm, midiOutGetErrorTextW)
DECLARE_PROXY(winmm, midiOutOpen)
DECLARE_PROXY(winmm, midiOutClose)
DECLARE_PROXY(winmm, midiOutPrepareHeader)
DECLARE_PROXY(winmm, midiOutUnprepareHeader)
DECLARE_PROXY(winmm, midiOutShortMsg)
DECLARE_PROXY(winmm, midiOutLongMsg)
DECLARE_PROXY(winmm, midiOutReset)
DECLARE_PROXY(winmm, midiOutCachePatches)
DECLARE_PROXY(winmm, midiOutCacheDrumPatches)
DECLARE_PROXY(winmm, midiOutGetID)
DECLARE_PROXY(winmm, midiOutMessage)
DECLARE_PROXY(winmm, midiInGetNumDevs)
DECLARE_PROXY(winmm, midiInGetDevCapsA)
DECLARE_PROXY(winmm, midiInGetDevCapsW)
DECLARE_PROXY(winmm, midiInGetErrorTextA)
DECLARE_PROXY(winmm, midiInGetErrorTextW)
DECLARE_PROXY(winmm, midiInOpen)
DECLARE_PROXY(winmm, midiInClose)
DECLARE_PROXY(winmm, midiInPrepareHeader)
DECLARE_PROXY(winmm, midiInUnprepareHeader)
DECLARE_PROXY(winmm, midiInAddBuffer)
DECLARE_PROXY(winmm, midiInStart)
DECLARE_PROXY(winmm, midiInStop)
DECLARE_PROXY(winmm, midiInReset)
DECLARE_PROXY(winmm, midiInGetID)
DECLARE_PROXY(winmm, midiInMessage)
/* Auxiliary audio support */
DECLARE_PROXY(winmm, auxGetNumDevs)
DECLARE_PROXY(winmm, auxGetDevCapsA)
DECLARE_PROXY(winmm, auxGetDevCapsW)
DECLARE_PROXY(winmm, auxSetVolume)
DECLARE_PROXY(winmm, auxGetVolume)
DECLARE_PROXY(winmm, auxOutMessage)
/* Mixer support */
DECLARE_PROXY(winmm, mixerGetNumDevs)
DECLARE_PROXY(winmm, mixerGetDevCapsA)
DECLARE_PROXY(winmm, mixerGetDevCapsW)
DECLARE_PROXY(winmm, mixerOpen)
DECLARE_PROXY(winmm, mixerClose)
DECLARE_PROXY(winmm, mixerMessage)
DECLARE_PROXY(winmm, mixerGetLineInfoA)
DECLARE_PROXY(winmm, mixerGetLineInfoW)
DECLARE_PROXY(winmm, mixerGetID)
DECLARE_PROXY(winmm, mixerGetLineControlsA)
DECLARE_PROXY(winmm, mixerGetLineControlsW)
DECLARE_PROXY(winmm, mixerGetControlDetailsA)
DECLARE_PROXY(winmm, mixerGetControlDetailsW)
DECLARE_PROXY(winmm, mixerSetControlDetails)
/* Timer support */
DECLARE_PROXY(winmm, timeGetSystemTime)
DECLARE_PROXY(winmm, timeGetTime)
DECLARE_PROXY(winmm, timeGetDevCaps)
DECLARE_PROXY(winmm, timeBeginPeriod)
DECLARE_PROXY(winmm, timeEndPeriod)
/* Joystick support */
DECLARE_PROXY(winmm, joyGetPosEx)
DECLARE_PROXY(winmm, joyGetNumDevs)
DECLARE_PROXY(winmm, joyGetDevCapsA)
DECLARE_PROXY(winmm, joyGetDevCapsW)
DECLARE_PROXY(winmm, joyGetPos)
DECLARE_PROXY(winmm, joyGetThreshold)
DECLARE_PROXY(winmm, joyReleaseCapture)
DECLARE_PROXY(winmm, joySetCapture)
DECLARE_PROXY(winmm, joySetThreshold)
DECLARE_PROXY(winmm, joyConfigChanged)
/* MCI support */
DECLARE_PROXY(winmm, mciSendCommandA)
DECLARE_PROXY(winmm, mciSendCommandW)
DECLARE_PROXY(winmm, mciSendStringA)
DECLARE_PROXY(winmm, mciSendStringW)
DECLARE_PROXY(winmm, mciGetDeviceIDA)
DECLARE_PROXY(winmm, mciGetDeviceIDW)
DECLARE_PROXY(winmm, mciGetDeviceIDFromElementIDA)
DECLARE_PROXY(winmm, mciGetDeviceIDFromElementIDW)
DECLARE_PROXY(winmm, mciGetErrorStringA)
DECLARE_PROXY(winmm, mciGetErrorStringW)
DECLARE_PROXY(winmm, mciSetYieldProc)
DECLARE_PROXY(winmm, mciGetCreatorTask)
DECLARE_PROXY(winmm, mciGetYieldProc)
/* Multimedia File I/O support */
DECLARE_PROXY(winmm, mmioStringToFOURCCA)
DECLARE_PROXY(winmm, mmioStringToFOURCCW)
DECLARE_PROXY(winmm, mmioInstallIOProcA)
DECLARE_PROXY(winmm, mmioInstallIOProcW)
DECLARE_PROXY(winmm, mmioOpenA)
DECLARE_PROXY(winmm, mmioOpenW)
DECLARE_PROXY(winmm, mmioRenameA)
DECLARE_PROXY(winmm, mmioRenameW)
DECLARE_PROXY(winmm, mmioClose)
DECLARE_PROXY(winmm, mmioRead)
DECLARE_PROXY(winmm, mmioWrite)
DECLARE_PROXY(winmm, mmioSeek)
DECLARE_PROXY(winmm, mmioGetInfo)
DECLARE_PROXY(winmm, mmioSetInfo)
DECLARE_PROXY(winmm, mmioSetBuffer)
DECLARE_PROXY(winmm, mmioFlush)
DECLARE_PROXY(winmm, mmioAdvance)
DECLARE_PROXY(winmm, mmioSendMessage)
DECLARE_PROXY(winmm, mmioDescend)
DECLARE_PROXY(winmm, mmioAscend)
DECLARE_PROXY(winmm, mmioCreateChunk)

inline void WINAPI WinmmProxy(const HMODULE winmm)
{
    /* Installable driver support */
    IMPLEMENT_PROXY(winmm, CloseDriver)
    IMPLEMENT_PROXY(winmm, OpenDriver)
    IMPLEMENT_PROXY(winmm, SendDriverMessage)
    IMPLEMENT_PROXY(winmm, DrvGetModuleHandle)
    IMPLEMENT_PROXY(winmm, GetDriverModuleHandle)
    IMPLEMENT_PROXY(winmm, DefDriverProc)
    /* Sound support */
    IMPLEMENT_PROXY(winmm, sndPlaySoundA)
    IMPLEMENT_PROXY(winmm, sndPlaySoundW)
    IMPLEMENT_PROXY(winmm, PlaySoundA)
    IMPLEMENT_PROXY(winmm, PlaySoundW)
    /* Waveform audio support */
    IMPLEMENT_PROXY(winmm, waveOutGetNumDevs)
    IMPLEMENT_PROXY(winmm, waveOutGetDevCapsA)
    IMPLEMENT_PROXY(winmm, waveOutGetDevCapsW)
    IMPLEMENT_PROXY(winmm, waveOutGetVolume)
    IMPLEMENT_PROXY(winmm, waveOutSetVolume)
    IMPLEMENT_PROXY(winmm, waveOutGetErrorTextA)
    IMPLEMENT_PROXY(winmm, waveOutGetErrorTextW)
    IMPLEMENT_PROXY(winmm, waveOutOpen)
    IMPLEMENT_PROXY(winmm, waveOutClose)
    IMPLEMENT_PROXY(winmm, waveOutPrepareHeader)
    IMPLEMENT_PROXY(winmm, waveOutUnprepareHeader)
    IMPLEMENT_PROXY(winmm, waveOutWrite)
    IMPLEMENT_PROXY(winmm, waveOutPause)
    IMPLEMENT_PROXY(winmm, waveOutRestart)
    IMPLEMENT_PROXY(winmm, waveOutReset)
    IMPLEMENT_PROXY(winmm, waveOutBreakLoop)
    IMPLEMENT_PROXY(winmm, waveOutGetPosition)
    IMPLEMENT_PROXY(winmm, waveOutGetPitch)
    IMPLEMENT_PROXY(winmm, waveOutSetPitch)
    IMPLEMENT_PROXY(winmm, waveOutGetPlaybackRate)
    IMPLEMENT_PROXY(winmm, waveOutSetPlaybackRate)
    IMPLEMENT_PROXY(winmm, waveOutGetID)
    IMPLEMENT_PROXY(winmm, waveOutMessage)
    IMPLEMENT_PROXY(winmm, waveInGetNumDevs)
    IMPLEMENT_PROXY(winmm, waveInGetDevCapsA)
    IMPLEMENT_PROXY(winmm, waveInGetDevCapsW)
    IMPLEMENT_PROXY(winmm, waveInGetErrorTextA)
    IMPLEMENT_PROXY(winmm, waveInGetErrorTextW)
    IMPLEMENT_PROXY(winmm, waveInOpen)
    IMPLEMENT_PROXY(winmm, waveInClose)
    IMPLEMENT_PROXY(winmm, waveInPrepareHeader)
    IMPLEMENT_PROXY(winmm, waveInUnprepareHeader)
    IMPLEMENT_PROXY(winmm, waveInAddBuffer)
    IMPLEMENT_PROXY(winmm, waveInStart)
    IMPLEMENT_PROXY(winmm, waveInStop)
    IMPLEMENT_PROXY(winmm, waveInReset)
    IMPLEMENT_PROXY(winmm, waveInGetPosition)
    IMPLEMENT_PROXY(winmm, waveInGetID)
    IMPLEMENT_PROXY(winmm, waveInMessage)
    /* MIDI audio support */
    IMPLEMENT_PROXY(winmm, midiOutGetNumDevs)
    IMPLEMENT_PROXY(winmm, midiStreamOpen)
    IMPLEMENT_PROXY(winmm, midiStreamClose)
    IMPLEMENT_PROXY(winmm, midiStreamProperty)
    IMPLEMENT_PROXY(winmm, midiStreamPosition)
    IMPLEMENT_PROXY(winmm, midiStreamOut)
    IMPLEMENT_PROXY(winmm, midiStreamPause)
    IMPLEMENT_PROXY(winmm, midiStreamRestart)
    IMPLEMENT_PROXY(winmm, midiStreamStop)
    IMPLEMENT_PROXY(winmm, midiConnect)
    IMPLEMENT_PROXY(winmm, midiDisconnect)
    IMPLEMENT_PROXY(winmm, midiOutGetDevCapsA)
    IMPLEMENT_PROXY(winmm, midiOutGetDevCapsW)
    IMPLEMENT_PROXY(winmm, midiOutGetVolume)
    IMPLEMENT_PROXY(winmm, midiOutSetVolume)
    IMPLEMENT_PROXY(winmm, midiOutGetErrorTextA)
    IMPLEMENT_PROXY(winmm, midiOutGetErrorTextW)
    IMPLEMENT_PROXY(winmm, midiOutOpen)
    IMPLEMENT_PROXY(winmm, midiOutClose)
    IMPLEMENT_PROXY(winmm, midiOutPrepareHeader)
    IMPLEMENT_PROXY(winmm, midiOutUnprepareHeader)
    IMPLEMENT_PROXY(winmm, midiOutShortMsg)
    IMPLEMENT_PROXY(winmm, midiOutLongMsg)
    IMPLEMENT_PROXY(winmm, midiOutReset)
    IMPLEMENT_PROXY(winmm, midiOutCachePatches)
    IMPLEMENT_PROXY(winmm, midiOutCacheDrumPatches)
    IMPLEMENT_PROXY(winmm, midiOutGetID)
    IMPLEMENT_PROXY(winmm, midiOutMessage)
    IMPLEMENT_PROXY(winmm, midiInGetNumDevs)
    IMPLEMENT_PROXY(winmm, midiInGetDevCapsA)
    IMPLEMENT_PROXY(winmm, midiInGetDevCapsW)
    IMPLEMENT_PROXY(winmm, midiInGetErrorTextA)
    IMPLEMENT_PROXY(winmm, midiInGetErrorTextW)
    IMPLEMENT_PROXY(winmm, midiInOpen)
    IMPLEMENT_PROXY(winmm, midiInClose)
    IMPLEMENT_PROXY(winmm, midiInPrepareHeader)
    IMPLEMENT_PROXY(winmm, midiInUnprepareHeader)
    IMPLEMENT_PROXY(winmm, midiInAddBuffer)
    IMPLEMENT_PROXY(winmm, midiInStart)
    IMPLEMENT_PROXY(winmm, midiInStop)
    IMPLEMENT_PROXY(winmm, midiInReset)
    IMPLEMENT_PROXY(winmm, midiInGetID)
    IMPLEMENT_PROXY(winmm, midiInMessage)
    /* Auxiliary audio support */
    IMPLEMENT_PROXY(winmm, auxGetNumDevs)
    IMPLEMENT_PROXY(winmm, auxGetDevCapsA)
    IMPLEMENT_PROXY(winmm, auxGetDevCapsW)
    IMPLEMENT_PROXY(winmm, auxSetVolume)
    IMPLEMENT_PROXY(winmm, auxGetVolume)
    IMPLEMENT_PROXY(winmm, auxOutMessage)
    /* Mixer support */
    IMPLEMENT_PROXY(winmm, mixerGetNumDevs)
    IMPLEMENT_PROXY(winmm, mixerGetDevCapsA)
    IMPLEMENT_PROXY(winmm, mixerGetDevCapsW)
    IMPLEMENT_PROXY(winmm, mixerOpen)
    IMPLEMENT_PROXY(winmm, mixerClose)
    IMPLEMENT_PROXY(winmm, mixerMessage)
    IMPLEMENT_PROXY(winmm, mixerGetLineInfoA)
    IMPLEMENT_PROXY(winmm, mixerGetLineInfoW)
    IMPLEMENT_PROXY(winmm, mixerGetID)
    IMPLEMENT_PROXY(winmm, mixerGetLineControlsA)
    IMPLEMENT_PROXY(winmm, mixerGetLineControlsW)
    IMPLEMENT_PROXY(winmm, mixerGetControlDetailsA)
    IMPLEMENT_PROXY(winmm, mixerGetControlDetailsW)
    IMPLEMENT_PROXY(winmm, mixerSetControlDetails)
    /* Timer support */
    IMPLEMENT_PROXY(winmm, timeGetSystemTime)
    IMPLEMENT_PROXY(winmm, timeGetTime)
    IMPLEMENT_PROXY(winmm, timeGetDevCaps)
    IMPLEMENT_PROXY(winmm, timeBeginPeriod)
    IMPLEMENT_PROXY(winmm, timeEndPeriod)
    /* Joystick support */
    IMPLEMENT_PROXY(winmm, joyGetPosEx)
    IMPLEMENT_PROXY(winmm, joyGetNumDevs)
    IMPLEMENT_PROXY(winmm, joyGetDevCapsA)
    IMPLEMENT_PROXY(winmm, joyGetDevCapsW)
    IMPLEMENT_PROXY(winmm, joyGetPos)
    IMPLEMENT_PROXY(winmm, joyGetThreshold)
    IMPLEMENT_PROXY(winmm, joyReleaseCapture)
    IMPLEMENT_PROXY(winmm, joySetCapture)
    IMPLEMENT_PROXY(winmm, joySetThreshold)
    IMPLEMENT_PROXY(winmm, joyConfigChanged)
    /* MCI support */
    IMPLEMENT_PROXY(winmm, mciSendCommandA)
    IMPLEMENT_PROXY(winmm, mciSendCommandW)
    IMPLEMENT_PROXY(winmm, mciSendStringA)
    IMPLEMENT_PROXY(winmm, mciSendStringW)
    IMPLEMENT_PROXY(winmm, mciGetDeviceIDA)
    IMPLEMENT_PROXY(winmm, mciGetDeviceIDW)
    IMPLEMENT_PROXY(winmm, mciGetDeviceIDFromElementIDA)
    IMPLEMENT_PROXY(winmm, mciGetDeviceIDFromElementIDW)
    IMPLEMENT_PROXY(winmm, mciGetErrorStringA)
    IMPLEMENT_PROXY(winmm, mciGetErrorStringW)
    IMPLEMENT_PROXY(winmm, mciSetYieldProc)
    IMPLEMENT_PROXY(winmm, mciGetCreatorTask)
    IMPLEMENT_PROXY(winmm, mciGetYieldProc)
    /* Multimedia File I/O support */
    IMPLEMENT_PROXY(winmm, mmioStringToFOURCCA)
    IMPLEMENT_PROXY(winmm, mmioStringToFOURCCW)
    IMPLEMENT_PROXY(winmm, mmioInstallIOProcA)
    IMPLEMENT_PROXY(winmm, mmioInstallIOProcW)
    IMPLEMENT_PROXY(winmm, mmioOpenA)
    IMPLEMENT_PROXY(winmm, mmioOpenW)
    IMPLEMENT_PROXY(winmm, mmioRenameA)
    IMPLEMENT_PROXY(winmm, mmioRenameW)
    IMPLEMENT_PROXY(winmm, mmioClose)
    IMPLEMENT_PROXY(winmm, mmioRead)
    IMPLEMENT_PROXY(winmm, mmioWrite)
    IMPLEMENT_PROXY(winmm, mmioSeek)
    IMPLEMENT_PROXY(winmm, mmioGetInfo)
    IMPLEMENT_PROXY(winmm, mmioSetInfo)
    IMPLEMENT_PROXY(winmm, mmioSetBuffer)
    IMPLEMENT_PROXY(winmm, mmioFlush)
    IMPLEMENT_PROXY(winmm, mmioAdvance)
    IMPLEMENT_PROXY(winmm, mmioSendMessage)
    IMPLEMENT_PROXY(winmm, mmioDescend)
    IMPLEMENT_PROXY(winmm, mmioAscend)
    IMPLEMENT_PROXY(winmm, mmioCreateChunk)
}

#endif // PROXY_H
